language: python

cache:
   directories:
      - $HOME/.cache/pip

env:
   - DJANGO_VERSION=1.8
   - DJANGO_VERSION=1.9

# Django 1.8 requires Python version >= 2.7
#
# Django 1.9 requires Python version >= 3.4
# if using Python 3
python:
   # Code uses either Django 1.8 or the
   # wsgrief library, which exists only
   # in Python 2.7.11 and Python 3.x
   - 2.7.11
   - 3.4
   - 3.5

matrix:
  include:
    - python: 2.7
      env: DJANGO_VERSION=1.8
    - python: 3.2
      env: DJANGO_VERSION=1.8
    - python: 3.3
      env: DJANGO_VERSION=1.8

before_install:
   - uname -a
   - free -m
   - df -h
   - ulimit -a
   - mkdir builds
   - pushd builds
   # Build into own virtualenv in order
   # to control the build environment
   - virtualenv --python=python venv
   - source venv/bin/activate
   - python -V
   - pip install --upgrade pip setuptools
   - pip install Django==$DJANGO_VERSION
   - popd

script: cd trollSite && python manage.py test
